### ISSUE TITLE
Faltan cargar los labels que es un requisito que pedimos para el repo doc.

### ISSUE THREAD

**Issue by susanrosito** [Alejandro214/freetable_doc#1]
Tienen que cargar los labels que mencionamos en este documento: https://docs.google.com/document/d/15ny0jipEwamYXmtIvXHFvLQibyngaSTJ22wvcGndiLA/edit#

**Comment by Alejandro214** [comment]
Hecho

**Comment by susanrosito** [comment]
Ahi los vi. Genial.
