### ISSUE TITLE
Modificar Pagina de Prueba de concepto.

### ISSUE THREAD

**Issue by susanrosito** [Alejandro214/freetable_doc#6]
1 - Al actor del diagrama de casos de uso le tienen que poner un nombre, tiene que tener una identidad. Mozo / Camarera.
2 - No se usan flechas. Sacarlas. 
3 - Yo creo que el caso de uso acá es 1 solo: Confirmar un pedido, que les parece?

4 - Les recomiendo que vuelvan a ver la diapo de Dodino: Lecciones aprendidas.
https://docs.google.com/presentation/d/1EWlhSUFJ3VnP42fgu_cvsOHZyVTR3rY1h9UB4a9nRWk/edit#slide=id.p

**Comment by Alejandro214** [comment]
Hecho

**Comment by susanrosito** [comment]
listo.
