### ISSUE TITLE
Falta el Diagrama de Arquitectura en la documentacion

### ISSUE THREAD

**Issue by susanrosito** [Alejandro214/freetable_doc#7]
El diagrama de arquitectura se hace con la prueba de concepto. Así que necesitan armar dicho diagrama para que ya este en la documentación. 
Agregar una nueva pagina que diga Diagrama de Arquitectura.

Acuérdensen que tiene que estar aplicado con 1 caso de uso.
Acá también habla de como armar bien el diagrama de Arquitectura:
https://docs.google.com/presentation/d/1EWlhSUFJ3VnP42fgu_cvsOHZyVTR3rY1h9UB4a9nRWk/edit#slide=id.g95de1c2ccf_0_234

**Comment by JuanG10** [comment]
Hecho.

**Comment by susanrosito** [comment]
Listo.
